### ISSUE TITLE
`14_open_loop_control.py` can not run properly

### ISSUE THREAD

**Issue by WANG-KUI-TJU** [NREL/ROSCO#404]
## Description
I didn't modify any files; I just ran `14_open_loop_control.py` and received 
 `Traceback (most recent call last):
  File "e:\Turbine\ROSCO\ROSCO\Examples\14_open_loop_control.py", line 163, in <module>
    main()
  File "e:\Turbine\ROSCO\ROSCO\Examples\14_open_loop_control.py", line 129, in main
    fastBatch.run_serial()
  File "E:\Turbine\ROSCO\ROSCO\rosco\toolbox\ofTools\case_gen\runFAST_pywrapper.py", line 317, in run_serial
    evaluate(c)
  File "E:\Turbine\ROSCO\ROSCO\rosco\toolbox\ofTools\case_gen\runFAST_pywrapper.py", line 436, in evaluate
    return fast.execute()
  File "E:\Turbine\ROSCO\ROSCO\rosco\toolbox\ofTools\case_gen\runFAST_pywrapper.py", line 116, in execute
    writer.update(fst_update=self.case)
  File "E:\Turbine\ROSCO\ROSCO\rosco\toolbox\ofTools\fast_io\FAST_writer.py", line 86, in update
    loop_dict(self.fst_update, [])
  File "E:\Turbine\ROSCO\ROSCO\rosco\toolbox\ofTools\fast_io\FAST_writer.py", line 61, in loop_dict
    loop_dict(vartree[var], branch_i)
  File "E:\Turbine\ROSCO\ROSCO\rosco\toolbox\ofTools\fast_io\FAST_writer.py", line 64, in loop_dict
    get_dict(self.fst_vt, branch_i[:-1])[branch_i[-1]] = get_dict(self.fst_update, branch_i[:-1])[branch_i[-1]]
  File "E:\Turbine\ROSCO\ROSCO\rosco\toolbox\ofTools\fast_io\FAST_writer.py", line 38, in get_dict
    return reduce(operator.getitem, branch, vartree)
KeyError: 'DISCON_in'`. 
This error seems to occur in the FAST_writer.get_dict() function. I looked at this function but I'm not sure how to resolve the issue.I found that the `IEA 15MW_OL.yaml` requires a file named `/Users/dzalkind/Downloads/pitch_LC2p2_4ROSCO.dat`. I don't have this file, and I'm not sure if the error is related to it. Of course, I'm also not certain if this is a bug.
 
### Code versions
- ROSCO V2.9.0

**Comment by dzalkind** [comment]
I think the input yaml is okay, but we should remove that file named to reduce confusion.  

I suspect this is an issue on Windows.  I noticed there is an `e:` drive and an `E:` drive, and I think the file reader is getting confused and unable to read the DISCON the first time through.  

I'm not sure at this point how to fix the issue.

**Comment by WANG-KUI-TJU** [comment]
> I think the input yaml is okay, but we should remove that file named to reduce confusion.
> 
> I suspect this is an issue on Windows. I noticed there is an `e:` drive and an `E:` drive, and I think the file reader is getting confused and unable to read the DISCON the first time through.
> 
> I'm not sure at this point how to fix the issue.

thanks, i will try again.
